spring:
  application:
    name: StreetFoodGo

  datasource:
    url: jdbc:postgresql://localhost:5432/streetfoodgo
    username: streetfoodgo
    password: streetfoodgo
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: "${MAIL_HOST:smtp.gmail.com}"
    port: "${MAIL_PORT:587}"
    username: "${MAIL_USERNAME:}"
    password: "${MAIL_PASSWORD:}"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000


server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

app:
  osrm:
    base-url: "${APP_OSRM_BASE_URL:http://localhost:5000}"
  jwt:
    issuer: "streetfoodgo-api"
    audience: "external-systems"
    secret: "${JWT_SECRET:Uh0WvRj5qs2sChP0dwTkky/VoudWSk0FVikEDDUKdRU=}"
    ttl-minutes: 60
  hua-noc:
    base-url: "${HUA_NOC_BASE_URL:http://localhost:8080/swagger-ui.html}"
  base-url: "${APP_BASE_URL:http://localhost:8080}"
  email:
    from: "${EMAIL_FROM:noreply@streetfoodgo.com}"
    verification:
      expiry-hours: 24


